// ...
const walletController = require('../controllers/wallet.controller'); // <-- UNCOMMENT THIS
const contactController = require('../controllers/contact.controller');
// ...
router.get('/health', (req, res) => {
  res.status(200).json({ status: 'API is healthy, wallet controller loaded!' });
});
//...
router.post('/wallet', walletController.createWallet); // <-- UNCOMMENT THIS
router.post('/wallet/:name', walletController.loadWallet); // <-- UNCOMMENT THIS
//...